== GIT glossary and concepts summary

* *revisions* : a revision behaves like a database transaction and contains one or more file modifications.

* *repository* : a repository holds the revisions added through the git commands along with an object store (index), configuration files and logs. +
    +
  Each repository can be bound to one (or more) remote repositories. This allows for decentralized repositories.
    +
    +
Usually, the current repository is called the `master` while the remote one is called `origin`. footnote:[not mandatory]

* GIT revisions are linked between one another 
by references footnote:[linked list of ref objects].
    +
    +
    It also has a small expression language to refer to those revisions. 
    +
    *TODO::Explain references and reflog.*
    
[source,git]
--
head^1

--
    

== Notes


- GIT does not store differences between files but their actual content in either text or binary.


- GIT indexes files with SHA1 (hash algorithm). This is very useful to detect how files are moved accross the working copy and thus keep the history intact.

* *working copy*: a folder on a user/developer machine containing the current state of work (modifications)

* *branch*: A linked list of revisions in the revision tree: 
    
    - A branch can be the root one 
    
    - or derive from a particular transaction (i.e. commit) at any point in the developments' lifecycle.


* *tag*: a tag gives a significant name to a particular revision (commit) => for extracting particular versions (production) and find it more easily.

